### ISSUE TITLE
Remaining Memory leaks and application crash at more than 2000 tree entries

### ISSUE THREAD

**Issue by dupeNoob** [JAM-Software/Virtual-TreeView#1001]
Hi.

When there are more than 2000 entries in the Virtual-TreeView and the window is closed on double click then the application crashes with memory leaks.

FastMM memory leaks:
5 - 12 bytes: TObject x 2
13 - 20 bytes: TList x 1, TThreadList x 1
21 - 28 bytes: Unbekannt x 1
37 - 44 bytes: TBaseVirtualTree.ChangeTreeStatesAsync$ActRec x 1
53 - 60 bytes: TWorkerThread x 1

Delphi Version: 10.2 (also in 10.4)
Virtual Tree View Version: 7.4

A small demo program is attached: [VTBug.zip](https://github.com/JAM-Software/Virtual-TreeView/files/5622215/VTBug.zip).

My assumption is that the TWorkerThread is performing something with the internal cache while the tree is destroyed.
The application doesn't crash at less than 2001 tree entries or when an Application.ProcessMessages is performed before the tree will be destroyed.

**Comment by joachimmarder** [comment]
> the application crashes with memory leaks.

We should focus in the crash first, the mem leaks are most like only a consequence of the crash.

But I don't see a crash here with latest Virtual TreeView source code and Delphi 10.4.1. I opened the project, pressed F9, pressed "Fill VT", double clicked the VT control. The application terminated without errors.

Can you send the call stack and exception type of the crash please?
Which version of Virtual TreeView are you using?

**Comment by antsiparovich** [comment]
We have same problem.
...
VirtualStringTree1.EndUpdate; // activate TWorkerThread with items more 2000
...
TBaseVirtualTreeCracker(lCurrentTree).ChangeTreeStatesAsync([tsValidating], [tsUseCache, tsValidationNeeded]); // execute TThread.Synchronize in ChangeTreeStatesAsync
Then switch to main thread, where VT is destroyed (see FormClose). After second call execute TBaseVirtualTreeCracker(lCurrentTree).ChangeTreeStatesAsync(EnterStates, [tsValidating, tsStopValidation]);
Thus sometimes we have AV

Delphi Version: 10.3 Update 1
Virtual Tree View Version: 7.3
[Projects.zip](https://github.com/JAM-Software/Virtual-TreeView/files/5630922/Projects.zip)

Stack from another programm
```
02.12.2020 19:25:32.004 [7488] OS exception occured: Access violation at address 0000000000000015 in module 'Console.exe'. Execution of address 0000000000000015
02.12.2020 19:25:32.005 [7488] (FFFFFFFFFFFFF015){Console.exe} [0000000000000015]
02.12.2020 19:25:32.005 [7488] [000000000041224E]{Console.exe} System.@DelphiExceptionHandler (Line 20257, "System.pas" + 53) + $D
02.12.2020 19:25:32.005 [7488] [00007FFB690C11CF]{ntdll.dll   } Unknown function at __chkstk + $11F
02.12.2020 19:25:32.005 [7488] [00007FFB6908A209]{ntdll.dll   } Unknown function at RtlRaiseException + $399
02.12.2020 19:25:32.005 [7488] [00007FFB690BFE3E]{ntdll.dll   } KiUserExceptionDispatcher + $2E
02.12.2020 19:25:32.005 [7488] (FFFFFFFFFFFFF015){Console.exe} [0000000000000015]
02.12.2020 19:25:32.101 [7308] EAccessViolation occured: Access violation at address 0000000000000015 in module 'Console.exe'. Execution of address 0000000000000015 at address $000000000054F611
02.12.2020 19:25:32.101 [7308] [0000000000412AF3]{Console.exe} System.@RaiseAtExcept (Line 21541, "System.pas" + 32) + $0
02.12.2020 19:25:32.101 [7308] [0000000000412B11]{Console.exe} System.@RaiseExcept (Line 21630, "System.pas" + 2) + $0
02.12.2020 19:25:32.101 [7308] [000000000054F611]{Console.exe} System.Classes.TThread.Synchronize (Line 15666, "System.Classes.pas" + 40) + $0
02.12.2020 19:25:32.101 [7308] [000000000054F7B0]{Console.exe} System.Classes.TThread.Synchronize (Line 15697, "System.Classes.pas" + 5) + $16
02.12.2020 19:25:32.101 [7308] [000000000118F094]{Console.exe} VirtualTrees.TBaseVirtualTree.ChangeTreeStatesAsync (Line 18407, "VirtualTrees.pas" + 3) + $1C
02.12.2020 19:25:32.101 [7308] [0000000001134C34]{Console.exe} VirtualTrees.WorkerThread.TWorkerThread.Execute (Line 177, "VirtualTrees.WorkerThread.pas" + 31) + $0
02.12.2020 19:25:32.101 [7308] [000000000054E673]{Console.exe} System.Classes.ThreadProc (Line 15048, "System.Classes.pas" + 18) + $E
02.12.2020 19:25:32.101 [7308] [00000000004136CD]{Console.exe} System.ThreadWrapper (Line 24888, "System.pas" + 9) + $7
02.12.2020 19:25:32.101 [7308] [00007FFB678E7BD4]{KERNEL32.DLL} BaseThreadInitThunk + $14
02.12.2020 19:25:32.101 [7308] [00007FFB6908CE51]{ntdll.dll   } RtlUserThreadStart + $21
```

**Comment by joachimmarder** [comment]
I just committed a patch, could you please check if it solves the problem for you?

**Comment by Petz73** [comment]
Hi Joachim,

Unfortunately the patch doesn't help. The problem still exists...
I think the Virtual Tree doesn't crash.
The crash is a result of the memory leaks and comes a little bit later in our program, because it's accesses the formerly freed memory of the VT objects.
And the VT Workerthread is still working and also accesses this freed memory...
With an Application.Processmessages (Delphi) before destroying the VT, I think, the WorkerThread has enought time (or can get an event?) to finish his work...

Henrik

**Comment by modersohn** [comment]
Hi,

out of interest, I had a look at the demo project too and could reproduce the crashes with FastMM4 and FullDebugMode.

From my understanding, it looks like `.InterruptValidation` which is called in `TBaseVirtualTree.Destroy` does not properly ensure that no validation code is execute anymore - the synchronized call in `TBaseVirtualTree.ChangeTreeStatesAsync` has not yet been processed and when it does later, the tree is already destroyed.

I was able to fix this by adding a call to `CheckSynchronize` after `.InterruptValidation` in `TBaseVirtualTree.Destroy`. I'm not sure if this is the **right** way to fix this, but with the current design (shared worker thread calling Trees via Synchronize) this seems to be required.

Let me know what you think.

Sebastian

**Comment by VladimirBartosh** [comment]
> 
> 
> I just committed a patch, could you please check if it solves the problem for you?

It could not, because the code passed to Synchronize is executed asynchronusly, and if it happens when the tree has already been destroyed, Self becomes invalid and both FStates and HandleAllocated will fail, or even worse: you might got 'lucky' so that the memory Self points at will still be available, HandleAllocated and FStates will still contain some valid-looking values, the check will pass, but executing DoStateChange will fail, because object's memory will have been overwritten already by that time, with VMT reference leading to some random memory.

To solve this, you must ensure that no code like this is scheduled to run or already running at the time TBaseVirtualTree.Destroy executes

**Comment by modersohn** [comment]
@VladimirBartosh: hence my suggestion of adding CheckSynchronize - that should ensure that the asynchronously called code is executed before the destructor continues.

**Comment by VladimirBartosh** [comment]
CheckSynchronize can also be not enough. Imagine this:
1. Thread 1(main):   TWorkerThread.AddTree puts a tree to the worker list, and wakes up the worker thread
2. Thread 2(worker):   TWorkerThread.Execute gets the tree from list, unlocks the list, and is now performing the check in ChangeTreeStatesAsync: 
`if (Self.HandleAllocated) then`
3. Thread 1:  the tree is destoryed, with CheckSynchronize being run against an epmty synchronize list. Also InterruptValidation would not remove the tree from worker list, because it isn't there already, and  `TWorkerThread.ReleaseThreadReference();` would not prevent TWorkerThread from continuing execution past ` while not Terminated do,` check, but would rather 'leak' it, setting its FreeOnTerminate value to True. 
4. Any thread reuses the former TBaseVirtualTree memory
5. Thread 2: TBaseVirtualTreeCracker(lCurrentTree).ChangeTreeStatesAsync resumes, putting the already invalid Self pointer to synchronize list
6. Some unpredictable, but most probably wrong things happen.

**Comment by modersohn** [comment]
Thanks for your input @VladimirBartosh - that is why I had my doubts about CheckSynchronize too.

The more I look at the code, the more it feels like the local `lCurrentTree` in `TWorkerThread.Execute` was added at a later stage and before that, it used FCurrentTree. Because if you look at `TWorkerThread.RemoveTree`, it calls `WaitForValidationTermination`, which also calls `CheckSynchronize` - but only if the FCurrentTree is removed. That now no longer happens because of the local `lCurrentTree`.

If I'm not mistaken that was introduced in #844 - so hopefully @joachimmarder can shed some light on why this was done.

**Comment by joachimmarder** [comment]
Unfortunately Delphi lacks the concept of a cancellation token:, which would help here.
https://quality.embarcadero.com/browse/RSP-10044

> The more I look at the code, the more it feels like the local lCurrentTree in TWorkerThread.Execute was added at a later stage
> [...]
> If I'm not mistaken that was introduced in #844 - so hopefully @joachimmarder can shed some light on why this was done

lCurrentTree was already there in the initial commit of the file in 2015. I don't see a connection to #844 here.
There is a comment which brings in relation to #434, which unfortunately was not moved from Google code for unknown reasons.

> That now no longer happens because of the local lCurrentTree.

Sorry, but I don't see why. lCurrentTree is assigned to FCurrentTree at the moment this tree gets processed. And even if you make the assignment of nil the last line, the problem reported here persists.

**Comment by joachimmarder** [comment]
Using `CheckSynchronize()` solved the problem here. The race condition above should not be an issue as the handle is already deallocated at this point.

**Comment by modersohn** [comment]
@joachimmarder, yes, you're right - `lCurrentTree` was already there before commit 0838277, but it was pretty much unused until then.

I'm trying to understand the intent the original code had. And `RemoveTree` clearly tries to ensure that the currently processed tree is finished by calling `WaitForValidationTermination`, which in turn calls the same `CheckSynchronize` you've now added to `TWorkerThread.ReleaseThreadReference`. (The extra condition that this is only done with toVariableNodeHeight was also added with the same commit)

The change in commit 0838277 as part of #844 is quite severe. Before that `FCurrentTree` was always the currently processed tree - now it is not anymore, because the local `lCurrentTree` is used. In fact `Execute` only sets `FCurrentTree` *after* it called `ChangeTreeStatesAsync` - so that `CheckSynchronize` call in `WaitForValidationTermination` won't help.

I can fix the crash of the test-case by @antsiparovich by changing the following things:

1. Move the `FCurrentTree` assignment in `Execute` before the `ChangeTreeStatesAsynch` call
2. Remove the if condition before the `CheckSynchronize` call in `WaitForValidationTermination`

Wouldn't you agree that this solution is easier to understand than your CheckSynchronize call in TWorkerThread.ReleaseThreadReference? In fact, if this is done, I think lCurrentTree can be removed completely, which would further simplify the code.

What do you think about adding this test-case to a Test project with DUnit or DUnitX? Sure it's not really a unit-test and you wouldn't be able to run these kind of tests from the command line, but I think it could help to avoid regressions in the future.

Last but not least: I don't understand why `HandleAllocated` is used as a sanity check (in your first commit for this issue but also in `ChangeTreeStatesAsync`). Is this still a leftover from back when window messages were used for synchronization? Because now with Synchronize I don't see why the window handle has any relevance.

**Comment by modersohn** [comment]
I was wondering why the test project from @antsiparovich was hanging on shutdown when used with FastMM and it turns out it wasn't hanging, but actually trying to report a leak if 10k UnicodeStrings.

The following code needs to be added to Unit3 to fix this:

```
procedure TForm3.VirtualStringTree1FreeNode(Sender: TBaseVirtualTree;
  Node: PVirtualNode);
var
  nodedata: PNodeData;
begin
  nodedata:= Sender.GetNodeData(Node);
  Finalize(nodedata^.item);
end;
```

**Comment by joachimmarder** [comment]
> Remove the if condition before the CheckSynchronize call in WaitForValidationTermination

`CheckSynchronize()` can cause odd call stacks and even side effects. So I use `CheckSynchronize()` only when absolutely necessary. That means, the condition should stay in my opinion.

> Last but not least: I don't understand why HandleAllocated is used as a sanity check (in your first commit for this issue but also in ChangeTreeStatesAsync). Is this still a leftover from back when window messages were used for synchronization?

That may be possible. But I still think it is necessary to prevent the code to be executed in case the control is being destroyed. In a quick test with the project above I got AVs when I simply commented this line. We could of course something `if csDestroying in ComponentState`.

**Comment by modersohn** [comment]
> > Remove the if condition before the CheckSynchronize call in WaitForValidationTermination
> 
> `CheckSynchronize()` can cause odd call stacks and even side effects. So I use `CheckSynchronize()` only when absolutely necessary. That means, the condition should stay in my opinion.

The thing is, with that condition being left there, my fix of getting rid of `lCurrentTree` causes a hang, because `WaitForValidationTermination` loops forever (understandably).

Your fix OTOH is quite fragile - it calls CheckSynchronize only once - and there's absolutely no guarantee that it will finish all synchronized code with that Tree.

> That may be possible. But I still think it is necessary to prevent the code to be executed in case the control is being destroyed. In a quick test with the project above I got AVs when I simply commented this line. We could of course something `if csDestroying in ComponentState`.

There is no way to find out if a control already *has been* destroyed, so it doesn't help much if you can find out if it's just in the process of being destroyed.

I'm pretty sure the reason why the `HandleAllocated` checks had been added back when, was not for checking for controls being destroyed - they were added as a safeguard before actually getting the Handle for window message synchronization - because of the obnoxious "Control '' has no parent window" exception.

And it's perfectly fine for a tree to not have a handle nor a parent window. Imagine having a DropDown component with a tree which you do all sorts of things with, before the user eventually drops down the control and the tree gets a parent, a window handle and finally becomes visible.

As the code is now, I agree with @VladimirBartosh: there are quite a few circumstances where the current WorkerThread code can possibly crash and IMHO the only way forward is to add test-cases, so you can gain a bit of confidence that new changes don't break things.

I've started a simple test-case based on the test project here and as soon as the worker thread is involved, crashes start to occur (because I'm repeating the test 100 times). The goal now is to get this running reliably. For anyone interested, I've checked in just the test-case on the develop/thread-tests branch of my fork (link below my comment).

**Comment by joachimmarder** [comment]
> so it doesn't help much if you can find out if it's just in the process of being destroyed.

This is not correct, it is important to ensure that no new method is queued in the main thread for this control if it is being destroyed, because CheckSynchronize is called in the context of the destructor.

> Your fix OTOH is quite fragile - it calls CheckSynchronize only once - and there's absolutely no guarantee that it will finish all synchronized code with that Tree.

I don't think calling it multiple times helps here. It is important to call it at the right moment (the destructor) and to make sure that no new methods are queued for this control afterwards.

> I'm pretty sure the reason why the HandleAllocated checks had been added back when, was not for checking for controls being destroyed - they were added as a safeguard before actually getting the Handle for window message synchronization

OK, I will change it to `if not (csDestroying in ComponentState)`

**Comment by joachimmarder** [comment]
> I've started a simple test-case based on the test project here and as soon as the worker thread is involved, crashes start to occur (because I'm repeating the test 100 times). The goal now is to get this running reliably. For anyone interested, I've checked in just the test-case on the develop/thread-tests branch of my fork (link below my comment).

Thanks for creating this. I added it to the official repository and ran the tests project several times, the tests always passed. Is your fork maybe missing some changes? Or has additional changes?

**Comment by modersohn** [comment]
> Thanks for creating this. I added it to the official repository and ran the tests project several times, the tests always passed. Is your fork maybe missing some changes? Or has additional changes?

Unfortunately that's not the reason you're not seeing the crashes. In the mean-time I found out that for me, it only crashes on Win32 in the debugger. It does not crash when run without the debugger and it does not crash with Win64, regardless of the debugger. I was really puzzled by this and even started considering a bug in the debugger, but what I found *very* odd is that I see the exact same behavior both with RX 10.1 Berlin and RX 10.4 Sydney. And as soon as I remove the SetChildCount, i.e. avoid that any WorkerThread is started, the crashes go away with Win32 too.

So it seems I was bit too optimistic about adding reliable test-cases, but I have not given up yet. I'll definitely also check the good old DUnit GUI Runner and if all else fails will actually create and display the forms from the test case here.

**Comment by modersohn** [comment]
> I don't think calling it multiple times helps here. It is important to call it at the right moment (the destructor) and to make sure that no new methods are queued for this control afterwards.

Well for one thing, since Synchronize is actually called twice in .Execute and the thread has no mechanism to detect a destroyed tree in between those calls, a single Synchronize might not be sufficient. Plus you can't rely on the fact that no other part of the application you're running in does some Synchronize stuff around the same time. That is why I'm so keen on going back to the while loop in `WaitForValidationTermination` and removing `lCurrentTree`. That would ensure Synchronize is called as often as needed until the Execute finally had a chance to clear FCurrentTree.

**Comment by joachimmarder** [comment]
> Plus you can't rely on the fact that no other part of the application you're running in does some Synchronize stuff around the same time. 

Well, I don't think the Virtual TreeView control is responsible to handle this for all other parts of some application.

> since Synchronize is actually called twice in .Execute 

Yes, but conditionally. It won't be executing if the `csDestroying` flag is set.

>and the thread has no mechanism to detect a destroyed tree in between those calls, a single Synchronize might not be sufficient. 
 
Please describe more detailed where you additionally would like to call `CheckSynchronize()`.

A call to `CheckSynchronize()` will dequeue all `Synchronize()`, not just one. Calling it more than once in the destructor won't change anything. Calling it multiple times before the execution of the destructor won't help anything as long as it is still executed in the destructor. Calling if after the destructor will still cause AVs as the control is then destroyed.

**Comment by modersohn** [comment]
Thanks for explicitly stating your line of thought, I should have done the same last night. 

I understand that `CheckSynchronize` will execute all the code that has been synchronized, but that doesn't help here, since only one `Synchronize` call from our single `WorkerThread` can be active at any given time - because these calls are blocking. 

Here's a sequence of things that I think is not properly covered by the current code:

1. A Tree is destroyed and calls `InterruptValidation` and from there `TWorkerThread.RemoveTree`
2. In `RemoveTree`, it gets the locked `FWaiterList.LockList`
3. `LockList` needs to wait for `Execute`, which has the list locked while extracting `lCurrentTree`. I realize this only happens if the validation was just started at that moment, but I think this is not impossible, especially if you're imagining multiple trees sharing that one `WorkerThread`.
4. Once `Execute` has unlocked the list `RemoveTree` can continue, `lCurrentTree` is our tree being destroyed but `FCurrentTree` is still `nil`.
5. In `RemoveTree`, the call to `WaitForValidationTermination` doesn't do much because `FCurrentTree` is `nil`. **Essentially, `RemoveTree` has not made sure that the tree is no longer processed, which it should IMO.**
6. Now the destructor carries on and calls `TWorkerThread.ReleaseThreadReference` which in turn calls `CheckSynchronize()` at the end.
7. Now exactly one piece of synchronized code from the `WorkerThread` *might* get executed as these `Synchronize` calls are blocking. Let's imagine it is the code in the initial `ChangeTreeStatesAsync`.
8. After `CheckSynchronize`, the tree carries on destroying itself, while the thread calls `DoValidateCache`.
9. From this point on, any code accessing the tree from the thread can crash - and checks for `csDestroying` won't be protecting you from that since even retrieving `ComponentState` could crash.
10. Since `DoValidateCache` might actually cause other `Synchronize` calls, e.g. via `MeasureItemHeight`, this synchronized  code will most definitely get executed only once our tree destructor has finished and will therefore potentially crash.

Now imagine my proposed code changes have been incorporated (no more `lCurrentTree`, unconditional `CheckSynchronize` in the while loop of `WaitForValidationTermination`):

5. In `RemoveTree`, the call to `WaitForValidationTermination` will wait for the thread to finish it's work with `FCurrentTree`. The numerous calls to `CheckSynchronize()` are required since `.Execute` can actually cause an undefined number of Synchronize() calls because of `DoValidateCache` an `MeasureItemHeight` and only one `Synchronize` call will be executed for every call to `CheckSynchronize()`. Once the thread has completed work with `FCurrentTree`, `RemoveTree` finishes and the destructor can safely carry on destroying the tree.

**Comment by modersohn** [comment]
My point 8 above is actually incorrect. The thread would not call `DoValidateCache`, because `tsStopValidation` has been set in `InterruptValidation` in step 1.

I wouldn't say that this invalidates my scenario though - the point remains that there is the potential that the thread carries on working with lCurrentTree that already could have been destroyed.

**Comment by modersohn** [comment]
I made some progress with the test-case:

1. The test now calls `CheckSynchronize` after the tree has been destroyed. This is required, since the Tests project is a console application and there's no `TApplication` which normally would call it.
2. With Win64 the test now crashes in the debugger **if you undo the relevant fix**, i.e. comment out the `CheckSynchronize` in `ReleaseThreadReference`.
3. Unfortunately the crashes do not make the tests fail and they are invisible when run outside of the debugger.
4. The reason for that is that the exceptions are raised in the thread and the thread is freed using `FreeOnTerminate`
5. The Win32 platform still behaves completely different for me. It raises different exceptions on the main thread, which make the tests fail, but only when run from the debugger. I have no explanation for that and would be highly interested to get input from others whether they are seeing the same thing or whether it behaves identical to Win64 for them.

This is not as good as I had hoped for, but still an improvement. If you'd like to incorporate the changes, let me please make a pull request, so my elaborate commit message gets transferred as well.

Now regarding the open issue of `RemoveTree` not ensuring that the removed tree has been completely processed:

6. If you re-activate your fix, the Win64 tests run fine without a problem
7. If you however add a `Sleep(1000)` in `.Execute` before the finally, the tests will start to crash again
8. Now this might seem totally unrealistic, but I think it demonstrates that the code has a *potential* to crash.
9. In practice it doesn't crash and AFAIU the reason for that is that in `TBaseVirtualTree.Destroy` the call to `Clear` takes much longer than the `WorkerThread` typically needs to finish. That is why none of the calls in `.Execute` encounter a tree already completely destroyed.
10. These crashes go away if I incorporate my proposed changes.

**Comment by joachimmarder** [comment]
> If you'd like to incorporate the changes, let me please make a pull request

I would be very interested, but isn't it you that needs to make a pull request? I never did it the other way round

> If you however add a Sleep(1000) in .Execute before the finally, the tests will start to crash again
> Now this might seem totally unrealistic, but I think it demonstrates that the code has a potential to crash.

I agree. If that would provoke a crash we could look for a solution for this. 

Earlier today I was thinking if it could make sense to set `FCurrenTree` to `nil` at a later point, but I was reluctant to do without evidence that this is necessary, as the code looks like this was done by intention.

**Comment by modersohn** [comment]
> I would be very interested, but isn't it you that needs to make a pull request? I never did it the other way round

Okay I'll make one - yesterday you got the test-case I started without a PR - don't know how, but somehow you managed ;-)

> I agree. If that would provoke a crash we could look for a solution for this.

Ok great - lets make the PR for the test first and then I can make another one with the fixes I'd propose.

> Earlier today I was thinking if it could make sense to set `FCurrenTree` to `nil` at a later point, but I was reluctant to do without evidence that this is necessary, as the code looks like this was done by intention.

I totally agree, every code change should have a clear motivation and in an ideal world, a repeatable test-case.

**Comment by joachimmarder** [comment]
> - yesterday you got the test-case I started without a PR - don't know how, but somehow you managed

Well, I copied the file. But this is not convenient in the long run and does not preserve the commit message, at least not without further manual copy&paste. Thanks for making the PR.

**Comment by modersohn** [comment]
Thanks for accepting the PR, that was fast!

I'm already preparing another test-case with toVariableNodeHeight and things are looking good right now.

Do you have ideas for more test-cases related to WorkerThread synchronization? One obvious thing would be cancelling a validation (and/or invalidating it while it's still running) - similar to what you mentioned in #915.

**Comment by joachimmarder** [comment]
> If you however add a Sleep(1000) in .Execute before the finally, the tests will start to crash again.

I tried that after merging you pull request, but did not see a crash. Run from inside the IDE with debugging two times.

**Comment by modersohn** [comment]
Yep - because my PR fixes it! If you undo the changes, it should start crashing!

**Comment by modersohn** [comment]
Was that Win32? Did you try Win64? The project is missing some UnitScope names for Win64 to compile correctly (same as Win32). 

I just tried again, reverting my fix commit 5aaba1e, added the `Sleep(1000)` in `.Execute` directly before the last finally and the AVs started to occur right away.

**Comment by joachimmarder** [comment]
It was Win64, no local changes compared to official repo.

**Comment by modersohn** [comment]
Actually, I'm completely at a loss why you can't see any of the exceptions (no exceptions on Win32 as well?). Could you please double check that Tools, Options, Debugger, Embarcadero Debuggers, "Ignore non-user breakpoints" is off and that only the usual Language exceptions are ignored and Native OS exceptions are set to Run unhandled by the debugger?

In the meantime, I've identified some reasons for the exception I saw under Win32 and fixed them (see new issues linked above). I'm still hunting one that is only happening with the new toVariableNodeHeight test-case.

**Comment by joachimmarder** [comment]
OK, I was finally able to see the exception.

I was able to fix it by assigning `FCurrentTree` before the call to `ChangeTreeStatesAsync()`. Can you please test this fix too for you?

**Comment by modersohn** [comment]
> OK, I was finally able to see the exception.

OK, great. It would be nice if you could let us know what made them appear. Did the fix for #1009 make them appear? Or was it caused by your IDE settings?

> I was able to fix it by assigning `FCurrentTree` before the call to `ChangeTreeStatesAsync()`. Can you please test this fix too for you?

I saw numerous AVs both with and without your fix. With your fix I actually also had deadlocks, because `WaitForValidationTermination` does not call `CheckSynchronize` while `Execute` was in `ChangeTreeStatesAsync`.

All of these are perfectly explainable and none of these occur with my proposed changes.

Could you please take the time and thoroughly read my comment from 6.12.2020 (https://github.com/JAM-Software/Virtual-TreeView/issues/1001#issuecomment-739480187)? Your fix affects my point 5 - now `WaitForValidationTermination` does wait, but it is deadlocking because the synchronized code in ChangeTreeStatesAsync is never executed.

I'd be grateful if you could have a look at my commit 8f7accc29c90fb9794d90f27319c3da7a186f9e1 - it's now in a separate branch for the tests. If you have objections to any of those code changes, then please state them clearly. I'm more than willing to add new test-cases for specific scenarios that you're worried about. If you prefer a pull request for the discussion, I'll create one.

Thank you.

**Comment by joachimmarder** [comment]
>  Or was it caused by your IDE settings?
I think it were IDE seetings.

> With your fix I actually also had deadlocks, because WaitForValidationTermination does not call CheckSynchronize while Execute was in ChangeTreeStatesAsync.

Agreed and changed.

> Could you please take the time

My time for this is a bit limited for this at the moment. I don't see a reason to rush this as the code is that way for a long time. Also doing changes more granular I am able to see how our automated tests react on the changes.

**Comment by modersohn** [comment]
Okay understood. More granular is not a bad idea.

Your code change eliminating `lCurrentTree` is very much appreciated - but at least in the online diff of 725e1fc - it reads as in finally you're still setting `FCurrentTree` to `nil` even though you're accessing it afterwards. I'm surprised this didn't crash when you tested it?

Finally - I wasn't aware there were other automated tests. Are these accessible somehow? I'd love to take a look.

**Comment by modersohn** [comment]
Ah I see this was fixed seconds later in a990b79c6091ffac424641cbe719d9a04c140680

**Comment by joachimmarder** [comment]
> .Execute does not Queue UpdateEditBounds, but calls everything in Synchronize directly. the Queue could also cause AVs, if it is eventually executed after  FCurrentTree had already been destroyed

Agreed and changed.

**Comment by joachimmarder** [comment]
> I wasn't aware there were other automated tests. Are these accessible somehow? 

No, these are unit and integration tests of some of JAM Software's products that use Virtual Treeview excessively. I was surprised that they did not reveal the original problem. But we also use MadExcept and also did not receive exception reports in this area as far as I know.

**Comment by joachimmarder** [comment]
> removed the CheckSynchronize in ReleaseThreadReference because there  is no longer a need for that, this late in the process

Agreed and changed.

> I'd be grateful if you could have a look at my commit 8f7accc - it's now in a separate branch for the tests.

I think I got all the relevant changes now. Thanks for submitting them

**Comment by modersohn** [comment]
> No, these are unit and integration tests of some of JAM Software's products that use Virtual Treeview excessively. I was surprised that they did not reveal the original problem. But we also use MadExcept and also did not receive exception reports in this area as far as I know.

I think the majority of the exceptions were invisible because of the combination of the threads using `FreeOnTerminate` and the missing exception handling in `.Execute`. I'm not sure that madExcept would catch these too.

> I think I got all the relevant changes now. Thanks for submitting them

Looks like it - the main difference being that you kept `ChangeTreeStatesAsync` and even extended it. Because I was agreeing with the comment that this should be moved to WorkerThread eventually this is what I essentially did.

**Comment by joachimmarder** [comment]
> the main difference being that you kept ChangeTreeStatesAsync and even extended it. Because I was agreeing with the comment that this should be moved to WorkerThread eventually this is what I essentially did.

I was not sure about that TODO, in any case I would like to have this done in a seperate commit.

**Comment by joachimmarder** [comment]
Well, our automated tests of last night revealed that a deadlock is back.

```
thread $1ea4:
7ff9f68c KERNELBASE.dll                                             SleepEx
005791a4 UltraSearch.exe System.Classes                             TThread.Sleep
016e1947 UltraSearch.exe VirtualTrees.WorkerThread         126   +4 TWorkerThread.WaitForValidationTermination
016e206b UltraSearch.exe VirtualTrees.WorkerThread         232  +11 TWorkerThread.RemoveTree
017274d9 UltraSearch.exe VirtualTrees                    13846   +5 TBaseVirtualTree.InterruptValidation
0174388f UltraSearch.exe VirtualTrees                    25713   +2 TBaseVirtualTree.ValidateCache
01745f4a UltraSearch.exe VirtualTrees                    26848  +24 TBaseVirtualTree.EndUpdate

thread $2298:
7ff9f68c KERNELBASE.dll                                      WaitForSingleObjectEx
0048e684 UltraSearch.exe System.SysUtils                     WaitForSyncWaitObj
0048e918 UltraSearch.exe System.SysUtils                     WaitOrSignalObj
00410d3e UltraSearch.exe System                              TMonitor.Wait
00410e2d UltraSearch.exe System                              TMonitor.Wait
00578d17 UltraSearch.exe System.Classes                      TThread.Synchronize
00578ecc UltraSearch.exe System.Classes                      TThread.Synchronize
01732d04 UltraSearch.exe VirtualTrees              18537  +3 TBaseVirtualTree.ChangeTreeStatesAsync
016e1d1d UltraSearch.exe VirtualTrees.WorkerThread   172 +30 TWorkerThread.Execute

```

So I'm going to revert one of the changes in TWorkerThread.Execute() for now.

> If you have objections to any of those code changes, then please state them clearly. I'm more than willing to add new test-cases for specific scenarios that you're worried about. 

Could you please describe why you think it is important to clear  `FCurrentTree` as last line of the finally block? That was the change that caused the deadlock.

**Comment by modersohn** [comment]
Okay thanks for sharing the call stack. I presume this is coming from madExcept and that it had the option enabled to detect deadlocked threads (don't remember the exact name though)? Could you post the general message madExcept logged besides the call stack?

The thing is - how is this a call stack of a dead lock? Sure it's not locking in `Sleep`, right? And the next command after `Sleep` would be the `CheckSynchronize` now called permanently in `WaitForValidationTermination` and that should actually allow the `WorkerThread` to finish it's `Synchronize` call.

I understand you want to revert it quickly to get your tests back running, but I'd really want to *understand* what's going on. If it's really an issue, it deserves a test-case, so any fixes can be checked against it.

> Could you please describe why you think it is important to clear `FCurrentTree` as last line of the finally block? That was the change that caused the deadlock.

There is nothing special about that last line. It is just that the `WorkerThread` *in general* should only work with `FCurrentTree` and not a hidden local variable. Because *only then* can `WaitForValidationTermination` actually detect that it needs to wait. If it doesn't, the tree might get destroyed and the thread could call methods of a destroyed object resulting in possible AVs.

**Comment by joachimmarder** [comment]
> The thing is - how is this a call stack of a dead lock? Sure it's not locking in Sleep, right? 

No, or curse not. It's simply not getting out of this loop `while FCurrentTree = Tree do`, because fCurrentTree is cleared later now.

> I presume this is coming from madExcept

Yes.

> Could you post the general message madExcept logged besides the call stack?

The MadExcept freeze detection hit here. I don't think the customizable MadExcept message for this case matters heres

> There is nothing special about that last line. It is just that the WorkerThread in general should only work with FCurrentTree and not a hidden local variable. 

I brought back this local variable to avoid the deadlock. Its itention isn't to hide something, but to have assigned `FCurrentTree` only in case the worker thread is truly working on this tree.

**Comment by modersohn** [comment]
> No, or curse not. It's simply not getting out of this loop `while FCurrentTree = Tree do`, because fCurrentTree is cleared later now.

Please explain while it would not get out of the loop? FCurrentTree should be cleared last so the loop waits long enough. The loop is not endless, because FCurrentTree is eventually cleared and the thread has a chance to continue because the loop now continually calls CheckSynchronize.

> > Could you post the general message madExcept logged besides the call stack?
> 
> The MadExcept freeze detection hit here. I don't think the customizable MadExcept message for this case matters heres

I didn't mean the custom text you might present to the user, but more details about what exactly did madExcept detect, after how many seconds and so on. Have you considered that madExcept's assumption that the thread is frozen might be incorrect?

> I brought back this local variable to avoid the deadlock. Its itention isn't to hide something, but to have assigned `FCurrentTree` only in case the worker thread is truly working on this tree.

I think there's still a fundamental misconception here. I can see no deadlock and yes by using lCurrentTree and not FCurrentTree, the worker thread is hiding the fact that it is still processing that tree. It is hiding this fact from WaitForValidationTermination and because of it, it's loop - which should not deadlock! - is exiting too early.

> only in case the worker thread is truly working on this tree.

What do you mean with "truly" here? Is setting the states not truly working? From my point of view, if the thread calls methods on a tree, it is working with it - so it must be avoided that the tree is destroyed.

**Comment by joachimmarder** [comment]
>  more details about what exactly did madExcept detect,

MadExcept reported an application freeze.

> after how many seconds 

We configured 60 seconds.

> Have you considered that madExcept's assumption that the thread is frozen might be incorrect?

Given that MadExcept was never wrong here in the past 10 years: No

> Please explain while it would not get out of the loop?

OK, sorry, it's not that easy to explain as I initially thought. My best guess at the moment is that the tree is added over and over again to the worker list while tree is being filled.

> I think there's still a fundamental misconception here.

That may indeed be the case. However, the old code worked fine for quite a while in our automated tests and for several hundred thousand users, so I have to revert these specific changes until we have a better solution for setting the flags as an atomic operation.

> What do you mean with "truly" here? Is setting the states not truly working?

The actual work that needs to be done is the call to `DoValidateCache()`. This is the code that we don't want to be entered twice for the same tree, for which the flags are used.

**Comment by joachimmarder** [comment]
The latest runs of our tests were fine again after the two reverts.  That leaves two questions:

- Why did the UI thread freeze with these changes?
- Which of the above repro projects is still failing with the current code?

**Comment by modersohn** [comment]
> MadExcept reported an application freeze.
> We configured 60 seconds.
> > Have you considered that madExcept's assumption that the thread is frozen might be incorrect?
> Given that MadExcept was never wrong here in the past 10 years: No

I'm surprised you're still having such a trust in your test cases. Also: you might wanna read up on freeze detection in madExcept's documentation. I'll just quote a teaser here:

> "You should use it for code blocks where the main thread is doing time consuming tasks without handling messages. Otherwise you're in danger of getting false freezing alarms"

I'd suggest you let your tests run without that madExcept option. If it's really a freeze, you'll see it anyway, right?

> OK, sorry, it's not that easy to explain as I initially thought. My best guess at the moment is that the tree is added over and over again to the worker list while tree is being filled.

In other words: there is no explanation right now.

> The actual work that needs to be done is the call to `DoValidateCache()`. This is the code that we don't want to be entered twice for the same tree, for which the flags are used.

There is no chance this is entered twice as a tree can never be twice in `FWaiterList`. The reason for the checks is that the thread needs to make sure it never calls methods on a tree that has already been destroyed.

> Why did the UI thread freeze with these changes?

It most definitely is waiting longer now - as long as it actually has to.

I see two possible ways moving forward. If the code really produces a freeze and because the failing tests are private to you, you need to come up with a minimal reproducible example and post that here. If you have such an example I'm more than willing to have a look and find a way to fix this the right way. If on the other hand you prefer to take the "works for me" approach then, to be blunt, my conclusion would be that my time is better spent moving away from VirtualTreeView.

**Comment by joachimmarder** [comment]
> I'm surprised you're still having such a trust in your test cases

You're suggesting we should distrust our test results just because the initial problem was not covered by our tests? This is ridiculous.

> I'd suggest you let your tests run without that madExcept option. If it's really a freeze, you'll see it anyway, right?

We have been able to replicate the app freeze in our project UltraSearch using manual steps. We will further analyze this in the next days.

**Comment by joachimmarder** [comment]
All we can say for the moment is that `CheckSynchronize()` does not work as expected in this scenario, it does not see the synchronized call, `SyncList` is `nil` but it shouldn't be:
![grafik](https://user-images.githubusercontent.com/10615289/102900179-37e76380-446c-11eb-97d8-6e190ea13e1e.png)

**Comment by joachimmarder** [comment]
Problem seems to be caused by `CheckSynchronize()` being called recursively, that means the call stack contains two calls of `CheckSynchronize()` that are totally independent of each other.  See my comments above that I avoid calling `CheckSynchronize()` unless truly necessary.

I think we should use thread synchronization here that does not rely on `TThread.Synchronize()` or Windows messages.

**Comment by modersohn** [comment]
We need a reproducible test-case. If you think you understand what's going on, it should be possible to reproduce.

> Problem seems to be caused by `CheckSynchronize()` being called recursively, that means the call stack contains two calls of `CheckSynchronize()` that are totally independent of each other. 

Why are 2 nested `CheckSynchronize` calls a problem? The code in `CheckSynchronize` clearly caters for this, by releasing `ThreadLock` before executing the synchronized code. 

Most importantly: how does this explain the "app freeze" that madExcept detected and that you saw?

A recursion in `CheckSynchronize` would mean some synchronized code caused another call to `CheckSychronize`, right? If this is the cause of the problem, when why is clearing `FCurrentTree` earlier solving the problem?

What exactly was the call-stack? Was it an endless recursion? That should result in a stack overflow pretty soon, did you see that? 

What was the call stack of the worker thread at that point?

>See my comments above that I avoid calling `CheckSynchronize()` unless truly necessary.

I don't see how this relates - `CheckSynchronize` is now called in a while loop. No recursion. It needs to be called as many times as needed until the the thread has finished processing that tree. If you don't call it often enough, the calls to `TThread.Synchronize()` in the thread might deadlock - as seen in the test-case I created.

> I think we should use thread synchronization here that does not rely on `TThread.Synchronize()` or Windows messages.

Wait a minute. Window messages? Isn't that exactly what was used originally, before you started switching to `TThread.Synchronize()` with #844?

**Comment by joachimmarder** [comment]
> Most importantly: how does this explain the "app freeze" that madExcept detected and that you saw?

The nested call to `CheckSynchronize()` did not see the call queued via `TThread.Synchronize()`. So the worker thread hang in `TThread.Synchronize()` and the UI thread hang in `TWorkerThread.WaitForValidationTermination()`.

> What was the call stack of the worker thread at that point?

```
TThread.Synchronize()
TBaseVirtualTree.ChangeTreeStatesAsync()
TWorkerThread.Execute()
```

>  If this is the cause of the problem, when why is clearing FCurrentTree earlier solving the problem?

Because the condition of the while-loop evaluated to False immediately: `while FCurrentTree = Tree do`

> Wait a minute. Window messages? Isn't that exactly what was used originally, before you started switching to TThread.Synchronize() with #844?

Yes, which is why I wrote that this i not an option.

**Comment by joachimmarder** [comment]
> I don't see how this relates - CheckSynchronize is now called in a while loop. No recursion. It needs to be called as many times as needed until the the thread has finished processing that tree.

Having many places in the code that call it increases the likelyhood of a nested call. And if the nested call is done in a loop, it will stay nested.

> Why are 2 nested CheckSynchronize calls a problem? 

If more than one element is in the queue (`SyncList`, see my screenshot above), nested calls won't see the other elements. Only the top-most call will see them.

**Comment by joachimmarder** [comment]
I wonder: Do we always need to wait when we call `InterruptValidation() / RemoveTree()` until processing is finished?  We obviously do in `Destroy()`, but also e.g. in `EndUpdate()`?

What happens in our case: We collect data asynchronously and invoke in the UI thread to fill the control with the data using `TThread.Queue()`. In this context `TBaseVirtualTree.EndUpdate()` is called which calls `ValidateCache()` which calls `InterruptValidation()`.

**Comment by modersohn** [comment]
First regarding your last comment:

> I wonder: Do we always need to wait when we call `InterruptValidation() / RemoveTree()` until processing is finished? We obviously do in `Destroy()`, but also e.g. in `EndUpdate()`?

No I would say EndUpdate does not necessarily need to wait for the processing to be finished. But then what happens to the tree while the validation is still running and the tree is no longer updating?

> What happens in our case: We collect data asynchronously and invoke in the UI thread to fill the control with the data using `TThread.Queue()`. In this context `TBaseVirtualTree.EndUpdate()` is called which calls `ValidateCache()` which calls `InterruptValidation()`.

Ah, that is a very interesting piece of information. So there is *another* thread that calls `EndUpdate` synchronized? And that eventually ends up in `WaitForValidationTermination` calling `CheckSynchronize` in a loop and that never sees anything in `SyncList` because the other `CheckSynchronize` call further up the call stack already had the Worker threads sync item in it's copied `LocalSyncList`? 

Now, for the first time, that does indeed make sense. And with that info it should be possible to reproduce this in a test-case. I'll give it a try later and will post my findings.

**Comment by modersohn** [comment]
Have just pushed the test-case in my fork on the develop/thread-tests branch.

If I understood you correctly, that call-stack should be quite similar to what you saw, right?

<img width="776" alt="image" src="https://user-images.githubusercontent.com/44807458/102994520-8275e800-451f-11eb-8b44-355bd0927ccd.png">

The difference here being that I call InterruptValidation directly, just to keep Begin/EndUpdate out of the way.

**Comment by modersohn** [comment]
I was able to fix the hanging test with this:

```
procedure TWorkerThread.WaitForValidationTermination(Tree: TBaseVirtualTree);
begin
  if (FCurrentTree <> Tree) or FWaitingForTermination then
    Exit;

  FWaitingForTermination:= True;
  try
    // Wait for any references to this tree to be released.
    while FCurrentTree = Tree do
    begin
      Sleep(1);
      CheckSynchronize(); //since Execute uses Synchronize, it must have a chance to finish; #1001
    end;
  finally
    FWaitingForTermination:= False;
  end;
end;
```

This assumes that `WaitForValidationTermination` is only called from the main thread, so a simple `Boolean` to avoid nesting should be sufficient.

I'm not sure that this is the ideal fix, but I also don't see any major drawbacks. If, for example, a `Destroy` would be called via a nested `Synchronize`, a crash or hang would be inevitable anyway.

**Comment by joachimmarder** [comment]
> If I understood you correctly, that call-stack should be quite similar to what you saw, right?

Here's our call stack of the freeze:

```
SleepEx
Sleep
TThread.Sleep
TWorkerThread.WaitForValidationTermination
TWorkerThread.RemoveTree
TBaseVirtualTree.InterruptValidation
TBaseVirtualTree.ValidateCache
TBaseVirtualTree.EndUpdate
TFileSearchPresenter.ProcessQueuedUpdates
TUpdateAggregator.Execute$ActRec.$2$Body
CheckSynchronize
TApplication.WndProc
TWinControl.MainWndProc
StdWndProc
DispatchMessageW
TApplication.ProcessMessage
TApplication.HandleMessage
TApplication.Run

```

Compared to yours there's only one call to `InterruptValidation()` in the stack, and it's pretty straightforward: Just an anonymous procedure that is queued in the main thread and fills the control.

**Comment by joachimmarder** [comment]
> I was able to fix the hanging test with this:

Sorry, but I don't see why this should help here: The first `CheckSynchronize()` call in the stack may still have the queue with >1 elements, and so the element that will make the while-loop terminate.

**Comment by modersohn** [comment]
> Sorry, but I don't see why this should help here:

Yes, thanks to the call-stack you now posted I can see that the fix would not work for this case.

That leaves us back at square one and I don't see how this could be prevented without fundamentally changing the design.

Again, back to your other question:
> I wonder: Do we always need to wait when we call `InterruptValidation() / RemoveTree()` until processing is finished? We obviously do in `Destroy()`, but also e.g. in `EndUpdate()`?

That would mean no longer calling `WaitForValidationTermination` in `RemoveTree`, but instead in `ReleaseThreadReference`, right?

At first glance that doesn't look like a bad idea, as the thread would just be left to finish the aborted validation before possibly fetching the same tree again from the list and doing a requested new validation (when called from `EndUpdate`).

But because `InterruptValidation` is called at so many different spots, it's very difficult to determine whether that change of behavior (immediate return instead of waiting) will be causing new problems. I also suspect that `State` management could be affected by this.

**Comment by joachimmarder** [comment]
> That would mean no longer calling WaitForValidationTermination in RemoveTree, but instead in ReleaseThreadReference, right?

No, just call `WaitForValidationTermination()` conditonally, based on a parameter value.

> But because InterruptValidation is called at so many different spots, it's very difficult to determine whether that change of behavior (immediate return instead of waiting) will be causing new problems.

Yes, that was my thinking too. But if we add a parameter with a default value, we don't need to change it in every place where `InterruptValidation()` is called.

**Comment by joachimmarder** [comment]
I've committed a possible fix, let me know what you think. 

> I also suspect that State management could be affected by this.

I think it boils down to the question: Do we need to wait for validation termination in `TBaseVirtualTree.ValidateCache()`?

**Comment by modersohn** [comment]
> I've committed a possible fix, let me know what you think.

I have only just looked at the code, but it seems your fix only applies to the single situation you saw - where `InterruptValidation` is called from `ValidateCache`. 

But there are many more calls to `InterruptValidation`, which still end up calling `WaitForValidationTermination` and which might therefore potentially end up in an endless `CheckSynchronize` loop.

Take for example a simple `SetChildCount` call and imagine that it is called from a thread with `Synchronize`. Early on it calls `InterruptValidation` too and that could never return if, again, the WorkerThread's `Synchronize` code and the `SetChildCount` code end up being fetched from `SyncList` at the same time.

I think the reason the caching code has been synchronized all the time (earlier via window messages and later with Synchronize/Queue) is the fact that all the stuff that is done in DoValidateCache is not thread-safe (I can elaborate on that if you disagree). 

Therefore, before the nodes are manipulated by any of the many routines called from the main thread, it must make sure that WorkerThread will no longer touch the nodes (what InterruptValidation does/did). If it doesn't - like now when called with False - the WorkerThread via DoValidateCache will end up potentially accessing freed memory with all of the consequences.

So basically, it is a catch 22: if you don't wait for WorkerThread to finish you will end up introducing more problems, but waiting for the thread might lead to problems too.

The only way out would be a truly thread-safe implementation of `DoValidateCache`, but I honestly don't see how this could be done.

**Comment by joachimmarder** [comment]
> I think the reason the caching code has been synchronized all the time (earlier via window messages and later with Synchronize/Queue) is the fact that all the stuff that is done in DoValidateCache is not thread-safe (I can elaborate on that if you disagree).

Of course the data model of Virtual TreeView and hence `DoValidateCache()` is not thread-safe. And making it thread-safe is not an option.

I think it would be sufficient to make writing and using `FStates` thrad-safe, but that is still a lot of work. 


> but it seems your fix only applies to the single situation you saw

I am aware of that. It was just to show the pattern and to ask the question: Can it cause any harm to not wait for validation termination in such situations?

If the answer is no, we could simply change the new parameter's default value or decide call by call if we need to wait.

**Comment by modersohn** [comment]
> I am aware of that. It was just to show the pattern and to ask the question: Can it cause any harm to not wait for validation termination in such situations?
> 
> If the answer is no, we could simply change the new parameter's default value or decide call by call if we need to wait.

To me the code contract of `InterruptValidation` is quite clear: it needs to wait for `WorkerThread` to finish, because the node structure is about to be changed, so `DoValidateCache` must not run anymore.

Now, you could argue, that within `ValidateCache`, it does not necessarily need to wait, because it is starting a new `DoValidateCache` anyway, but that's beside the point: `ValidateCache` is called *after* the node structure has been manipulated, so at that point, the validation shouldn't be running anyway - and that is exactly why `ValidateCache` is mostly called in methods that started off by calling `InterruptValidation` - see SetChildCount and many others.

> I think it would be sufficient to make writing and using `FStates` thrad-safe, but that is still a lot of work.

I don't think that would be sufficient. Essentially you would need to be able to avoid any call to `Synchronize` within `WorkerThread`, but that seems impossible to me. `DoValidateCache` will always need `Synchronize` for `MeasureItemHeight` and the thread itself needs to handle exceptions with `Synchronize`.

I really see no way out of this - with the current design, the validation needs to be fully cancelled and both ways in which that has been tried (messages and synchronize) have failed. And I'm not aware of a third option one could try.

**Comment by joachimmarder** [comment]
> I really see no way out of this - with the current desig

I agree. To me it seems the best solution would be if `CheckSynchronize()` would retain the order of the queued elements and would dequeue only one element. If we agree here, I will open an issue at Embarcadero's Quality Portal.

**Comment by pyscripter** [comment]
I have been watching this issue with interest.

I don't think that Embarcadero is likely to change the way Synchronize works any time soon, especially since this is not a bug.  Another solution needs to be found.

**Comment by pyscripter** [comment]
> I think it would be sufficient to make writing and using `FStates` thrad-safe, but that is still a lot of work.

System.Threading has the following code for lock free state update:

```pascal
function TParallel.TLoopState.TLoopStateFlag.AtomicUpdate(NewState, InvalidStates: TLoopStateFlagSet; var OldState: TLoopStateFlagSet): Boolean;
var
  SW: TSpinWait;
begin
  SW.Reset;
  repeat
    OldState := FLoopStateFlags;
    if OldState * InvalidStates <> [] then
      Exit(False);
    if TInterlocked.CompareExchange(Integer(FLoopStateFlags), Integer(NewState + OldState), Integer(OldState)) = Integer(OldState) then
      Exit(True);
    SW.SpinCycle;
  until False;
end;
```

Can we do somethiing similar for ChangeTreeStatesAsync to avoid using synchronize?

However there is the following code:

```pascal
        if (tsValidating in FStates) and (tsValidating in LeaveStates) then
          UpdateEditBounds();
```

Can this be avoided by invalidating or something similar?

**Comment by pyscripter** [comment]
The bigger question I wanted to ask is whether this threaded validation is worth the trouble.
- Only used when VisibleCount > 2000  -  How common that is?  Is the count the total number of nodes in the tree or just the
visible ones (currently shown)?
- ThreadWorker.Execute often calls indirectly Synchronize and InterruptValidation with the  loop containing Sleep and CheckSynchronize  is costly.  Do you have any benchmark or at least a feeling of the benefits of threaded validation on the user experience?

**Comment by modersohn** [comment]
> I agree. To me it seems the best solution would be if `CheckSynchronize()` would retain the order of the queued elements and would dequeue only one element. If we agree here, I will open an issue at Embarcadero's Quality Portal.

Honestly, I didn't even consider this possibility, also because I think the chances are very high that Embarcadero will just consider this "as designed". If you want to take the chances and report it, I would highly recommend including a solid test-case, but even then, my hopes aren't high. Also I'd refrain from suggesting how this should be fixed and leave it up to them, but that is just my personal experience with bug reporting.

**Comment by modersohn** [comment]
> * Only used when VisibleCount > 2000  -  How common that is?  Is the count the total number of nodes in the tree or just the
>   visible ones (currently shown)?

In `ValidateCache`, `CacheThreshold` is compared to `FVisibleCount`, so yes, only the ones currently shown.

> * ThreadWorker.Execute often calls indirectly Synchronize and InterruptValidation with the  loop containing Sleep and CheckSynchronize  is costly.  Do you have any benchmark or at least a feeling of the benefits of threaded validation on the user experience?

This is not about absolute objective performance, but about *subjective* performance for the user. If you manipulate a large tree while positioned at the top, there is little that needs to be done to be able to update the GUI and let normal operation continue. 

The positional cache is necessary to speed up things like vertical scrolling and hit-testing, which gets even more complicated, if variable node height is involved. Imagine a tree with a million visible nodes and you're positioned at the very end. Just adding a single node makes it necessary to iterate through all of them to determine the exact position of the last node. If you'd do this synchronously, the tree would feel very sluggish.

If you want to see this in action, have a look at the Advanced Demo and enable state tracking in the secondary window (this is also a demonstration why state change events need to be synchronized).

> Can we do somethiing similar for ChangeTreeStatesAsync to avoid using synchronize?

Even if we could, that doesn't solve the problem. The validation of the position cache is walking the tree nodes in a separate thread. It has to be aborted before any changes are made to the nodes, otherwise crashes and undetermined behavior are guaranteed to happen, even if not always reproducible.

**Comment by joachimmarder** [comment]
> so yes, only the ones currently shown.

Just to avoid a misunderstanding here: This does not mean the nodes visible in the current viewport, but all nodes that are not in collapsed branches. So it's not unlikely.

> Can we do somethiing similar for ChangeTreeStatesAsync to avoid using synchronize?

That's unfortunately not sufficient, as @modersohn wrote earlier. And I also agree with him that this code makes sense. 

I don't think it would be an overall benefit to remove this code. For what it's worth: With the latest code I am unable to replicate any of the AVs or mem leaks reported above.

**Comment by modersohn** [comment]
> For what it's worth: With the latest code I am unable to replicate any of the AVs or mem leaks reported above.

Yes, but the fixes feel very circumventional (i.e. 2 calls to `CheckSynchronize` because `WorkerThread.Execute` calls `Synchronize` twice - an assumption that is not necessarily true all the time etc.).

But I understand you need a workable solution right now - for a long term solution, I'd like to invite you all to post some feedback to the proposed thread-less alternative I described in #1014

**Comment by pyscripter** [comment]
The catch22 is that the WorkerThread is using Synchronize indirectly in two places:
- ChangeTreeStatesAsync
- MeasureItemHeight for variable height trees

This is why InterruptValidation, called from the main thread has to use CheckSynchronize and the issues that this has.

The solution is to avoid using Synchronize.   Then, InterruptValidation can do a standard wait using some simple synchronization mechanism.

ChangeTreeStatesAsync can be changed to not use Synhronize as indicated above.  It can use the suggested lock-free mechanism and UpdateEditBounds is not an issue since it does nothing when called from a thread different than main.  

So the only problem is MeasureItemHeight .  I have not looked into this, but you use the WorkerThread only for trees with uniform height.

If you agree that this is the right direction and I can submit a PR.

**Comment by modersohn** [comment]
> The solution is to avoid using Synchronize. Then, InterruptValidation can do a standard wait using some simple synchronization mechanism.

Your idea certainly has merit, but the task of completely avoiding `Synchronize` is not easy to achieve (see below).

> ChangeTreeStatesAsync can be changed to not use Synhronize as indicated above. 

While your proposed code would be able to change `FState` in a thread-safe manner, it would no longer call `DoStateChange`, therefore not firing the `OnStateChange` event (and not doing the `Assert` there).

> It can use the suggested lock-free mechanism and UpdateEditBounds is not an issue since it does nothing when called from a thread different than main.

The fact that `UpdateEditBounds` does nothing when called from a different thread is just a safety measure. But the edit position needs to be updated with the new position information once the position cache is updated.

> So the only problem is MeasureItemHeight . I have not looked into this, but you use the WorkerThread only for trees with uniform height.

One could certainly disable asynchronous validation when `toVariableNodeHeight` is set, but that is a limitation that doesn't exist right now and I'm not sure how common that would be.

Let's see if and how we can work out the remaining issues.

**Comment by modersohn** [comment]
Oh and there's one case for `Synchronize` that I forgot: how do you do exception handling in the thread without `Synchronize`, given the fact that you a) want the thread to carry on working after an exception and b) it might be released with `FreeOnTerminate = True`, meaning there's nobody who could re-raise `TThread.FatalException` in the main thread?

**Comment by pyscripter** [comment]
> how do you do exception handling in the thread without `Synchronize`,

You can always shut the thread down raise the Exception and start a new WorkerThread when needed, or use Queue instead of synchronize.

In fact this is another change I want to see implemented:  Use queue instead of synchronize in the WorkerThread exception handling.

**Comment by modersohn** [comment]
> You can always shut the thread down raise the Exception and start a new WorkerThread when needed, or use Queue instead of synchronize.

Who would shut it down and raise the exception? Imagine the thread already has a list of several trees waiting for validation - how would you be able to manage all of this? I can't see how.

> In fact this is another change I want to see implemented: Use queue instead of synchronize in the WorkerThread exception handling.

Again, that would not solve the synchronization problems, I think. The exception is acquired to a local variable in `Execute` and then captured for the anonymous method passed to `Synchronize`. How would this work if `Queue` is used instead and by the time someone processes this with CheckSynchronize, the thread has long been gone?

**Comment by pyscripter** [comment]
> Who would shut it down and raise the exception? Imagine the thread already has a list of several trees waiting for validation - how would you be able to manage all of this? I can't see how.

In this case the list of trees would be stored inside a global thread-safe list.  The Terminate event could schedule the start of a new worker thread.

> Again, that would not solve the synchronization problems, I think. The exception is acquired to a local variable in `Execute` and then captured for the anonymous method passed to `Synchronize`. How would this work if `Queue` is used instead and by the time someone processes this with CheckSynchronize, the thread has long been gone?

This is if, as now, the WorkerThread stays around till shutdown. 

> t would no longer call `DoStateChange`, therefore not firing the `OnStateChange`

This however is a problem but may be acceptable since the only states that ChangeTreeStatesAsync changes have to do with validation and could be considered as internal and of no interest to the user.  You also could use a different enumeration TValidationState or TCacheState, that is stored in a separate field instead of including them in State.

**Comment by modersohn** [comment]
> The Terminate event could schedule the start of a new worker thread.

The `OnTerminate` event is called with `Synchronize`, so we're back to square one.

The exception handling with Queue might actually work if the compiler is smart enough to capture the exception correctly even when the thread has already been freed. I'm going to try that later with a test-case and memory leak detection enabled.

> This however is a problem but may be acceptable since the only states that ChangeTreeStatesAsync changes have to do with validation and could be considered as internal and of no interest to the user. You also could use a different enumeration TValidationState or TCacheState, that is stored in a separate field instead of including them in State.

That is certainly something to consider, but it does change the current behavior in quite a substantial way - since you never know who uses the OnStateChange event for whatever reason. Therefore renaming and moving the state to a separate enum is certainly the preferable approach as it would intentionally break any code out there that does work with these states.

**Comment by pyscripter** [comment]
> The `OnTerminate` event is called with `Synchronize`, so we're back to square one.

But there is no need to wait for that.  You could instead start a new FreeOnTerminate WorkerThread  before exiting the existing one.

> The exception handling with Queue might actually work if the compiler is smart enough to capture the exception correctly even when the thread has already been freed.

You could instead store the Exception in a private field of the Tree. and raise it in the queued anonymous method.    It is important to avoid using synchronize.

**Comment by joachimmarder** [comment]
I would like to close this issue in case none of the above issues can be reproduced anymore. I don't claim that this is a good solution, but it is at least some solution. Please continue discussions about alternative designs in issue #1014.

**Comment by obones** [comment]
I'm sorry to be the bringer of bad news, but I found about this issue because we are facing its exact consequences, despite having updated to today's git content.
What I have found, though, is that the code in the destructor only needs a little alteration to fix our issue. Currently, the code is like this:

```
  WasValidating := (tsValidating in FStates);
  InterruptValidation(True);
  if WasValidating then
  begin
    // Make sure we dequeue the two synchronized calls from ChangeTreeStatesAsync(), fixes mem leak and AV reported in issue #1001, but is more a workaround.
    CheckSynchronize();
    CheckSynchronize();
  end;// if
```

Our fix is to change it to this:

```
  WasValidating := ([tsValidating, tsValidationNeeded] * FStates <> []);
  InterruptValidation(True);
  if WasValidating then // Make sure we dequeue the synchronized calls from ChangeTreeStatesAsync(), to avoid mem leak and AV reported in issue #1001
    while CheckSynchronize() do
      Sleep(1);
```

First, we discovered that our our VTV instance was in the `tsStopValidation, tsValidationNeeded` state, not the `tsValidating` one. Maybe it's the presence of `tsStopValidation` that should be checked along `tsValidating`, I'm not sure.
Second, the `CheckSynchronize` method returns `True` if it has processed a method call. It is much safer to continue calling it while it returns `True` because there might be many other calls from outside the VTV pending in the queue. Doing a very short `Sleep` in the loop is here to ensure we yield to the other threads.

With this, the issue is fixed for good.

**Comment by joachimmarder** [comment]
> First, we discovered that our our VTV instance was in the tsStopValidation, tsValidationNeeded state, not the tsValidating one. 

Are you sure that the `TWorkerThread` was blocked in a `ChangeTreeStatesAsync()`?  I currently cannot imagine how this could happen. The whole thing is done to ensure that the `tsValidating` flag correctly and thread-safe indicates if the tree is being validated.

> Second, the CheckSynchronize method returns True if it has processed a method call. It is much safer to continue calling it while it returns True because there might be many other calls from outside the VTV pending in the queue. Doing a very short Sleep in the loop is here to ensure we yield to the other threads.

Yes, this makes a lot of sense, and I am committing this code change now. One idea would be to do this as long as the `tsValidating` flag is set. Thanks for submitting this idea.

**Comment by obones** [comment]
> Are you sure that the `TWorkerThread` was blocked in a `ChangeTreeStatesAsync()`? I currently cannot imagine how this could happen. The whole thing is done to ensure that the `tsValidating` flag correctly and thread-safe indicates if the tree is being validated.

At the time the destructor is called, `TWorkerThread` is blocked waiting for the `Synchronize` call inside `ChangeTreeStatesAsync()` to return. And when this happens, the VTV instance has its state property set to `[tsStopValidation, tsValidationNeeded]`. With the current code, the calls to `CheckSynchronize` are never done and seconds later I get an access violation inside the anonymous method of `ChangeTreeStatesAsync()` right on the call to `DoStateChange` because the VTV has already been destroyed.

Note that the blocked call to `ChangeTreeStatesAsync()` originates from `TWorkerThread.Execute` and more precisely the first one that does this: 

    TBaseVirtualTreeCracker(lCurrentTree).ChangeTreeStatesAsync([tsValidating], [tsUseCache, tsValidationNeeded]);

So, at the time the destructor is called, `tsValidating` has not yet been added to the states of the VTV instance because the worker thread is waiting for our main thread to process the `Synchronize` calls. This also means that looping while `tsValidating` is in `FStates` would not loop at all because it will only appear in `FStates` after the first `Synchronize` call has had a chance to occur.

Note that out of `tsStopValidation` and `tsValidationNeeded` that are both present in `FStates`, I decided to settle on `tsValidationNeeded` for my change to `WasValidating` value, but it would work just as well with `tsStopValidation`. This is where I have a doubt and I believe you have a better understanding of the various flags and the more appropriate one to use on top of `tsValidating` which clearly is not enough on its own.

**Comment by joachimmarder** [comment]
> Note that the blocked call to ChangeTreeStatesAsync() originates from TWorkerThread.Execute and more precisely the first one that does this:

OK, yes, although it seems unlikely, the `TWorkerThread` may of course get stuck here in the first call to ChangeTreeStatesAsync(). I changed TBaseVirtualTree.Destroy() accordingly.
