### ISSUE TITLE
Caret disappears if toShowStaticText option is enabled

### ISSUE THREAD

**Issue by 7even11** [JAM-Software/Virtual-TreeView#547]
If toShowStaticText option (StringOptions) is true, when pressing F2 (to rename the node), the caret is not shown. If toShowStaticText is false, pressing F2 shows the caret normally.

The issue does not manifest under Windows XP (themes off, default theme) and does manifest under Windows 7 or Windows 8.x

![vstbug2](https://cloud.githubusercontent.com/assets/2266850/7456397/7c5fc3da-f284-11e4-9eec-55f7ff6305c9.png)

**Comment by joachimmarder** [comment]
This issue is similar to #159, which was fixed for V5.3.0.

**Comment by joachimmarder** [comment]
Cannot reproduce this on my Windows XP with Virtual Treeview V6 and Delphi XE8.

**Comment by 7even11** [comment]
Please close this issue. I have tried with V5.5.3 (was using 5.2.2) and the problem is fixed. I assumed the problem is still there but should have tried the latest version before reporting it.
