### ISSUE TITLE
Dropdown button is not painted for ctButton

### ISSUE THREAD

**Issue by supasoft** [JAM-Software/Virtual-TreeView#886]
See screenshot
![2019-03-18_15-40-11](https://user-images.githubusercontent.com/40602544/54531191-bfe63280-4995-11e9-822e-d25f6fc979e1.png)

**Comment by joachimmarder** [comment]
I don't se a dropdown button in the screenshot. Please describe the expected and actual behavior more exactly and include the used version of Virtual TreeView.

**Comment by supasoft** [comment]
CheckType "ctButton" does not work. See source and screenshot.
![2019-03-19_16-27-28](https://user-images.githubusercontent.com/40602544/54611406-ef656f80-4a67-11e9-862f-4fffe83f6191.png)
[vt button.zip](https://github.com/Virtual-TreeView/Virtual-TreeView/files/2983690/vt.button.zip)

**Comment by joachimmarder** [comment]
Sorry, I now understand the problem, I never used ctButton myself so far. With issue #867 the imageglist `UtilityImages` was removed, I guess the down arrow was part of this list.

**Comment by joachimmarder** [comment]
I committed a fix but did not have much time to test it. Please let me know if it works for you.

**Comment by supasoft** [comment]
The button is painted now, but OnChecked still does not work.

**Comment by joachimmarder** [comment]
> The button is painted now, but OnChecked still does not work.

This is a button, not a checkbox. Did this use to work in earlier versions of VTV? Furthermore the OnChecked event is only fired if the check state changes, but this condition won't get true for a button. However, I can force this in `DetermineNextCheckState()`.
